### ISSUE TITLE
Enum is not generated

### ISSUE THREAD

**Issue by Bissector** [gristlabs/ts-interface-builder#4] opened 2018-10-25 06:44 UTC
Hi,

I like this tool a lot, but I hit a limitation I can't work around. My interfaces are generated from other service and I can't refactor them to avoid enums. And, as header says, enums are not generated properly by ts-interface-builder.

interface and enum source:
```
export interface LimitInput {
  amount: number;
  period?: Period | null;
  periodEnds?: string | null;
}
export enum Period {
  MONTH = "MONTH",
  WEEK = "WEEK",
}
```

generated checkers:
```
export const LimitInput = t.iface([], {
  "amount": "number",
  "period": t.opt(t.union("Period", "null")),
  "periodEnds": t.opt(t.union("string", "null")),
});
const exportedTypeSuite: t.ITypeSuite = {
  LimitInput
};
```
As you see Period enum is used in validation, but is not included in ```exportedTypeSuite```. Is this a bug? Or are there any options I can use to include enums in output? Do I miss something?

Thanks!

**Comment by dsagal** [comment] 2018-10-25 19:36
It's not a bug, it's just that it's not implemented. It allows you to implement Period yourself. I.e. you can work around it by adding an implementation for your enum when creating the [ts-interface-checker](https://github.com/gristlabs/ts-interface-checker) validation checkers:

```
import {createCheckers, ICheckerSuite} from 'ts-interface-checker';
import {basicTypes, BasicType} from 'ts-interface-checker/dist/types';

import typeSuite from './your-file-ti';
typeSuite["Period"] = new BasicType((v) => ["MONTH", "WEEK"].includes(v), "is not a valid Period");
// OR typeSuite["Period"] = basicTypes["string"];

export const checkers = createCheckers(typeSuite);
checkers.LimitInput.check(DATA);
```

You'd need to produce your own implementation to check if the value is one of the allowed values. Or just use `basicTypes["string"]` to make Period an alias to string.

**Comment by 0fork** [comment] 2018-10-26 08:01
@dsagal what are you plans about implementing all types (outside those technically not feasible)? Just to clarify, this is not a demand or even a request - I'm just thinking about whether to start using the library and it would be useful to know your thoughts and plans so I can set my expectations right :) Thanks!

**Comment by Bissector** [comment] 2018-10-26 09:21
@dsagal , sorry I used the wrong word :) I am aware of the fact that enums might be just not implemented, intentionally or not. Thank you for your answer.

For me personally if I need to write enum checkers manually ruins the whole point that I define my data structure once and everything else is generated. In our project I **type** only GraphQL data structure, then we generate JSON schema representing GQL schema, then generate Typescript interfaces from our GQL queries and JSON schema and then I expect to generate TS-interface runtime checkers all automatically. This allow to avoid potential sync mistakes and unnecessary keyboard workouts :)

So, what are your plans for enums if any? I am sorry I can't contribute enum support myself. I like your approach and I'd like to stick with it in my project. But if enums will remain unsupported I will try different approach and libraries, like generating JSON schema from Typescript interfaces and validating objects at runtime against JSON schema using 'ajv' or similar.

Let me know please about your plans and thank you for developing this tool of yours!

**Comment by dsagal** [comment] 2018-10-26 17:47
OK OK, I think it's not too hard. I'll give it a shot :)

**Comment by dsagal** [comment] 2018-10-27 05:32
Enum support added in v0.1.6 of ts-interface-builder, and v0.1.5 of ts-interface-checker. Closing this request, but please open a new one if it's not enough for what you need.

**Closed by dsagal** 2018-10-27 05:32 UTC
